version: '3.8'


services:
    shortcut:
        container_name: shortcut
        build: .
        volumes:
        - ./:/firstsite
        ports:
        - 8000:8000
        env_file:
        - .env.dev
        depends_on:
        - db
        environment:
        - DB_HOST=db
        - DB_NAME=shortcut
        - DB_USER=admin
        - DB_PASSWORD=secret
        - DJANGO_SETTINGS_MODULE=settings.dev
        command:
            sh -c 'wait-for-it.sh db:5432 && python manage.py runserver 0.0.0.0:8000'

    db:
        image: postgres
        restart: always
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        environment:
           - POSTGRES_DB=shortcut
           - POSTGRES_USER=admin
           - POSTGRES_PASSWORD=secret

volumes:
        postgresql-data:






