version: '3.8'


services:
    shortcut:
        container_name: shortcut
        build: .
        volumes:
        - ./:/firstsite
        ports:
        - 8000:8000
        env_file:
        - .env.dev
        depends_on:
        - database
        command:
            sh -c 'wait-for-it.sh database:5432 && python manage.py runserver 0.0.0.0:8000'

    database:
        image: postgres
        restart: always
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        environment:
           - POSTGRES_DB=shortcut
           - POSTGRES_USER=admin
           - POSTGRES_PASSWORD=secret
        ports:
            - 5433:5432
volumes:
        postgresql-data:






