  version: '3.8'


  services:
    shortcut:
        container_name: shortcut
        build: .
        volumes:
        - ./:/firstsite
        ports:
        - 8000:8000
        env_file:
        - .env.dev
        depends_on:
        - db
        command:
            sh -c 'wait-for-it.sh db:5432 && python manage.py runserver 0.0.0.0:8000'

    db:
        image: postgres:13
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        environment:
           - POSTGRES_DB=shortcut
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=supersecretpassword
        ports:
            - 5433:5432
  volumes:
       postgresql-data:




