# Generated by Django 3.1.7 on 2021-03-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20210323_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
