# Generated by Django 3.1.7 on 2021-03-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20210323_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
