# Generated by Django 2.2.12 on 2021-04-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_auto_20210402_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='user',
        ),
    ]
