# Generated by Django 2.2.12 on 2021-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_remove_linkmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
