# Generated by Django 2.2.12 on 2021-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
