# Generated by Django 2.2.12 on 2021-04-08 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortcut', '0031_auto_20210405_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
