# Generated by Django 2.2.12 on 2021-04-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0032_auto_20210408_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
