# Generated by Django 3.1.7 on 2021-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('cut', models.CharField(max_length=255)),
                ('road', models.IntegerField(verbose_name='TIMES')),
            ],
        ),
    ]
