# Generated by Django 3.1.7 on 2021-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='cut',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='road',
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
