# Generated by Django 3.1.7 on 2021-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_linkmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='cuttinglink',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
