# Generated by Django 3.1.7 on 2021-03-23 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0007_auto_20210323_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='counter',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
