# Generated by Django 3.1.7 on 2021-03-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20210323_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='counter',
        ),
    ]
