# Generated by Django 3.1.7 on 2021-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_linkmodel_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='cuttinglink',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='updated',
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='short_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
