# Generated by Django 3.1.7 on 2021-03-24 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_auto_20210324_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
