# Generated by Django 2.2.12 on 2021-03-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_linkmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
