# Generated by Django 2.2.12 on 2021-04-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_auto_20210331_2008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linkmodel',
            unique_together={('link',)},
        ),
    ]
