# Generated by Django 2.2.12 on 2021-04-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_auto_20210402_1749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linkmodel',
            unique_together=set(),
        ),
    ]
