# Generated by Django 2.2.12 on 2021-04-02 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0026_auto_20210402_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
