# Generated by Django 2.2.12 on 2021-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20210402_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
