# Generated by Django 2.2.12 on 2021-04-02 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0028_auto_20210402_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
