# Generated by Django 2.2.12 on 2021-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_auto_20210402_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
