# Generated by Django 2.2.12 on 2021-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_auto_20210405_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
